### ISSUE TITLE
[1.10.2] Holy crap log spam on chunk genning

### ISSUE THREAD

**Issue by b0bst3r** [CAD97/SpawnerCraft#11]
Practically makes world genning grind to a complete halt, is this necessary???

http://pastebin.ubuntu.com/23467590/

SpawnerCraft 1.10.2-3.3.0

**Comment by CAD97** [comment]
Oops, debug code made it to prod

**Comment by CAD97** [comment]
I'll push a fix in about an hour

**Comment by CAD97** [comment]
Fix is live

1.10.2: https://minecraft.curseforge.com/projects/spawnercraft/files/2344305
1.9.4: https://minecraft.curseforge.com/projects/spawnercraft/files/2344306

**Comment by b0bst3r** [comment]
Thanks that stopped it :D
