### ISSUE TITLE
SMP Wither Skeleton and Skeleton Drops

### ISSUE THREAD

**Issue by bjaydubya** [CAD97/SpawnerCraft#13]
Hello, I have installed the latest on my SMP and all mobs drop essence except wither skeletons and normal overworld skeletons.  If there is anything I can do to help you see this issue (invite you to the server or produce logs), please let me know. Thanks!

**Comment by CAD97** [comment]
If your logs contain `cad97` or `spawnercraft` (case insensitive) anywhere in them, those lines (and context) would be helpful to me. Similarly, a list of installed mods.

Unfortunately, I'm quite busy at the moment, so I don't know when I'll be able to get around to testing this. Sorry for the inconvenience!

**Comment by bjaydubya** [comment]
Thanks for at least taking a look :).  Here is a link to the pastebin of the logs.  I purposefully tried to kill some wither skeletons and regular skeletons with the mob fishing rod.  I did kill one blaze in there just to compare against when it does work. [https://pastebin.com/DXSCAX72](https://pastebin.com/DXSCAX72)
![clientside](https://cloud.githubusercontent.com/assets/19522300/24536280/a14b4b74-1596-11e7-84f9-d3469fae1025.PNG)
![serverside](https://cloud.githubusercontent.com/assets/19522300/24536281/a14c36c4-1596-11e7-8dd6-e356d92fea03.png)

Also, the screenshots of my mod folders, both server side and client side (since they differ slightly).  

Thanks again :).  Hopefully you'll have time to update to 1.11.2 in the near future.  I really want to keep it when we are ready to update to 1.11.2 as soon as RTG is updated.

**Comment by CAD97** [comment]
Note to future me:

```
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.monster.EntitySkeleton.func_82202_m()I
    at cad97.spawnercraft.handler.DropsListener.getCustomIdFor(DropsListener.java:63) ~[DropsListener.class:?]
    at cad97.spawnercraft.handler.DropsListener.dropFor(DropsListener.java:49) ~[DropsListener.class:?]
    at cad97.spawnercraft.handler.DropsListener.onMobDrops(DropsListener.java:43) ~[DropsListener.class:?]
```

See https://github.com/CAD97/SpawnerCraft/blob/1.10/src/main/java/cad97/spawnercraft/handler/DropsListener.java#L63

Apparently `EntitySkelleton::getSkeletonType` doesn't believe exist on the server? Need to test locally.

This should be an easy fix. I'll see if I can fix it earlier, but I should be able to get to it by Easter weekend.

Related, there's only really one blocker on getting the 1.11 branch working, which is mostly just a matter of me getting time to fix the resource change. Hopefully I can get to that at the same time.

**Comment by CAD97** [comment]
If this happens with Strays as well (you may not have even known they're supposed to drop their own essence), then this is almost certainly the issue. I'll just have to shadow the client-only code into the server.

**Comment by bjaydubya** [comment]
I'll check if I get the same error with strays. Also, if the resources you need to update are graphic ones, let me know.  I do have a custom Vanilla+ resource pack I have been working on for some time and I'd be happy to try and help.  If it's code related, I doubt I could help much.

**Comment by bjaydubya** [comment]
Confirmed same issue on stray.  Can upload the log to pastebin, but it says the same thing.

**Comment by bjaydubya** [comment]
I'm a bit embarrassed, but if you look at the mods list, I have the correct version on the server, but for some reason I have 1.9.4-3.3.1 on my client...I updated that to the 1.10.2 version and it worked as advertised.  The offer still stands to help on resources if they are graphic related, however.  I would love to upgrade this to 1.11.2 when we RTG updates.  Thanks again for your effort in creating this mod.
