### ISSUE TITLE
Integration with Tough As Nails - Freeze Mob

### ISSUE THREAD

**Issue by dannydjdk** [CAD97/SpawnerCraft#16]
I added SpawnerCraft to a pack that also has Tough As Nails which has a mob called a Freeze which does have a spawn egg. However, there was no essence or spirit item for this mob. Vanilla mobs and mobs from the Quark mod were appearing, so I suspect Tough As Nails is registering the mobs differently.

Are you able to add support for this mob?

Versions:
Minecraft 1.10.2
SpawnerCraft 3.3.1
Tough As Nails 1.1.1
Forge 12.18.3.2185

Modpack: [Real Tech](https://minecraft.curseforge.com/projects/real-tech?gameCategorySlug=modpacks&projectID=257012)

Let me know if there is any additional info I can provide.

Thanks!

**Comment by CAD97** [comment]
You can see when using <kbd><kbd>F&zwnj;3</kbd>+<kbd>H</kbd></kbd> to show advanced tooltips, you can see that:

The Spawn Eggs for which I am producing Essence are `minecraft:spawn_egg`, and the Tough as Nails Freeze has its spawn egg as `toughasnails:spawn_egg`. Unfortunately, this means that I do not have the means to handle this within this mod.

I've [opened an issue](https://github.com/Glitchfiend/ToughAsNails/issues/259) over at Tough As Nails to use MCForge's spawn egg registry, which will allow their spawn eggs to be picked up properly.

It appears that you are the owner of the mod pack in question, so at least we won't have to wait for that layer to push the fix, just TAN. 🙃

**Comment by dannydjdk** [comment]
Thanks for opening the issue with TAN! They did fix it for their Minecraft 1.12 version. Unfortunately, they are not likely to fix it for 1.11.2 or 1.10.2, though they would accept a push request. I do plan to move the pack to 1.11.2 soon, but 1.12 is probably way off.

**Comment by CAD97** [comment]
Closing. I don't see any real way forward on this issue. I will investigate the possibility of adding custom essence via configuration in the future, though.
