### ISSUE TITLE
Add config to whitelist/blacklist certain mobs [suggestion]

### ISSUE THREAD

**Issue by siskulous** [CAD97/SpawnerCraft#17]
I love this mod, but sometimes it feels a bit OP and cheaty. For instance, setting a vindicator farm next to a trading hall fed by a villager spawner gets a bit insane, and a wither skeleton farm can quickly produce a full stack of wither skulls. 

It would be better if you could disallow certain mobs in worlds where you want more balance. Making this configurable should keep everyone happy by keeping current functionality.

**Comment by CAD97** [comment]
A whitelist could be nice, but a blacklist was quick to add. I'll investigate a whitelist before releasing full 4.0.0.

I'll see if I can push out another beta today or tomorrow so you can get this, as I'm going to be on vacation for a couple weeks starting Saturday.

**Comment by CAD97** [comment]
The syntax in the config file:

```cfg
general {
    B:"Toggle Essence Blacklist Mode"=true
    S:"Toggle Essence Validity" <
        minecraft:villager
        minecraft:zombie
     >
}
```

The above will blacklist `minecraft:villager` and `minecraft:zombie` from dropping essence. Setting `Toggle Essence Whitelist Mode` to `true` will mean that the list is instead a whitelist, with only mobs on the list dropping essence.

This can also be done from the client when the client has the power to change the configuration.
