### ISSUE TITLE
[1.12] - Caused by: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

### ISSUE THREAD

**Issue by Protheus** [CAD97/SpawnerCraft#19]
Game crashes after 5s.

**Pastebin**: https://pastebin.com/9z9MXsSQ
**Forge**: 2395
SpawnerCraft 1.12-4.0.0

What should happen: Game should load without crashing

**Comment by CAD97** [comment]
That was.... unexpected.

I built against 2387, and (I think, anyway) it works there.

I'm not even using anything scala, why would it break there...?

It's in [`<clinit>`](https://stackoverflow.com/a/8517155/3019990) as well which makes this even stranger.

If I weren't right there in the crash report I'd be likely to blame someone else, but I'm looking at it now. If gradle will cooperate and actually build my project, anyway...

**Comment by CAD97** [comment]
Just confirmed game loads with Forge 2387 (still the current recommended) just fine (at least in development). Updating to 2395...

**Comment by CAD97** [comment]
Confirmed this happens with the built jar.... oops.... what the heck is going on

**Comment by CAD97** [comment]
It launches fine in development. This might be a bit difficult to track down.

**Comment by CAD97** [comment]
FRICK

still don't know why it's breaking, but I found the offending line. I had somehow imported `scala.actors.threadpool.Arrays` instead of `java.util.Arrays`. And it worked in development (for some reason) and not when built (for some reason).

¯\\\_(ツ)\_/¯

The offending import is present in the 1.11 code as well, so I'll be removing that from there as well.

**Comment by CAD97** [comment]
Builds with the fix are uploading now.

- SpawnerCraft 4.0.0b3 for Minecraft 1.11.2
- SpawnerCraft 4.0.0b1 for Minecraft 1.12

I've also yanked the offending versions to hopefully mean that people won't run into this unnecessarily.

**Comment by Protheus** [comment]
:-) you're a star !
