### ISSUE TITLE
Enhance spawner drop configuration granularity

### ISSUE THREAD

**Issue by josephcsible** [CAD97/SpawnerCraft#3]
Currently, empty spawners always drop by default, but they can be configured to only drop when silk touch is used. Can a new option be added that would make them never drop?

**Comment by HoldYourWaffle** [comment]
It would also be nice to add an option to require a certain level of silk touch (and ofcourse adding that level into the game if it's not already in there)

**Comment by CAD97** [comment]
Yes, it would not be difficult to add an option to not drop Empty Spawners from regular Mob Spawners. I'd never really considered it previously as my main thought process went off of them not being craftable.

I'll look into the higher levels of Silk Touch, though I probably won't add the higher levels myself, I should allow fair play with a mod that does. I'll see if I can figure that out.

**Comment by CAD97** [comment]
Version 3.2 is out with the addition of this feature. http://minecraft.curseforge.com/projects/spawnercraft/files
