### ISSUE TITLE
mob essence isn't working 

### ISSUE THREAD

**Issue by largestjayce** [CAD97/SpawnerCraft#4]
we made a server put a few mods in everything workon the spawnercraft except mob essence drops

**Comment by CAD97** [comment]
I'm going to need a mod list of the server at the very least. Also: can I see the spawnercraft.config file? If you haven't changed it from default, you need to use a Mob Fishing Rod to make mobs drop Essence.

**Comment by CAD97** [comment]
Merging into #5, as it gives a specific reproduce case. As it turns out this is indeed a problem within the mod itself, but I will prefer the better bug report.

Watch #5 for updates; this is being worked on currently.

**Comment by CAD97** [comment]
Version 3.2 is out with the fix to this issue. http://minecraft.curseforge.com/projects/spawnercraft/files
