### ISSUE TITLE
1.10.2 not dropping empty spawner

### ISSUE THREAD

**Issue by JosEffigy** [CAD97/SpawnerCraft#6]
could this be a conflict with the following mods?
Ender IO
Actually Additions
edit: they drop with silk touch. it isnt stated in the documentation

**Comment by CAD97** [comment]
I'll do a pass on updating the docs this weekend. If you'd rather Spawners drop even without silk touch, there's a config for it.

In fact, I may have inadvertently changed the default when I changed the way that was handled. If I did, I will fix that come the next patch update.
