### ISSUE TITLE
Item ID for mob fishing rod?

### ISSUE THREAD

**Issue by JustCallMeToy** [CAD97/SpawnerCraft#9]
im messing around with this is single player and im trying to put OP enchantments on it. is there an official ID for the fishing rod? this might be a stupid question.. im just starting to learn command blocks...

**Comment by CAD97** [comment]
You shouldn't need the item ID for enchanting with commands: the command is `/enchant <PLAYER> <ENCHANTMENT> <LEVEL>`.

But here's the full list of mod item ids:

```
spawnercraft:mobRod
spawnercraft:mobCage
spawnercraft:mobSpirit
spawnercraft:mobEssence
spawnercraft:mobAgglomeration
```

When Forge 1.11 comes along, I'll probably update these ids to use `snake_case` instead of `camelCase` to fit the Minecraft example.
